const colors = {
  light: {
    text: "#2D1B4E",
    tint: "#7B5EA7",
    background: "#F5F1FF",
    foreground: "#2D1B4E",
    card: "#EDE8FF",
    cardForeground: "#2D1B4E",
    primary: "#7B5EA7",
    primaryForeground: "#FFFFFF",
    secondary: "#6FA870",
    secondaryForeground: "#FFFFFF",
    muted: "#E8E0F8",
    mutedForeground: "#5C4A7A",
    accent: "#A988D4",
    accentForeground: "#FFFFFF",
    destructive: "#D94040",
    destructiveForeground: "#FFFFFF",
    border: "#D5C9EF",
    input: "#D5C9EF",
  },
  dark: {
    text: "#EEE8FF",
    tint: "#A988D4",
    background: "#160E28",
    foreground: "#EEE8FF",
    card: "#241838",
    cardForeground: "#EEE8FF",
    primary: "#A988D4",
    primaryForeground: "#FFFFFF",
    secondary: "#6FA870",
    secondaryForeground: "#FFFFFF",
    muted: "#2A1D3E",
    mutedForeground: "#B8A8D0",
    accent: "#7B5EA7",
    accentForeground: "#FFFFFF",
    destructive: "#EF5555",
    destructiveForeground: "#FFFFFF",
    border: "#3A2658",
    input: "#3A2658",
  },
  radius: 16,
};

export default colors;
