export type District = { label: string; value: string };
export type Province = { label: string; value: string; districts: District[] };

const d = (label: string): District => ({ label, value: label });

export const TURKEY_PROVINCES: Province[] = [
  { label: "Adana",          value: "Adana",          districts: [d("Seyhan"), d("Çukurova"), d("Yüreğir"), d("Sarıçam"), d("Ceyhan"), d("Kozan"), d("İmamoğlu"), d("Karaisalı"), d("Karataş"), d("Pozantı"), d("Tufanbeyli")] },
  { label: "Adıyaman",       value: "Adıyaman",        districts: [d("Merkez"), d("Besni"), d("Kahta"), d("Gölbaşı")] },
  { label: "Afyonkarahisar", value: "Afyonkarahisar",  districts: [d("Merkez"), d("Sandıklı"), d("Dinar"), d("Emirdağ"), d("Bolvadin")] },
  { label: "Ağrı",           value: "Ağrı",            districts: [d("Merkez"), d("Doğubayazıt"), d("Patnos"), d("Diyadin")] },
  { label: "Aksaray",        value: "Aksaray",         districts: [d("Merkez"), d("Güzelyurt"), d("Ortaköy"), d("Eskil")] },
  { label: "Amasya",         value: "Amasya",          districts: [d("Merkez"), d("Merzifon"), d("Suluova"), d("Taşova")] },
  { label: "Ankara",         value: "Ankara",          districts: [d("Çankaya"), d("Keçiören"), d("Mamak"), d("Yenimahalle"), d("Sincan"), d("Etimesgut"), d("Altındağ"), d("Pursaklar"), d("Beypazarı"), d("Polatlı"), d("Gölbaşı"), d("Kahramankazan"), d("Haymana"), d("Nallıhan"), d("Kızılcahamam"), d("Bala"), d("Şereflikoçhisar"), d("Güdül"), d("Akyurt"), d("Çamlıdere"), d("Evren"), d("Kalecik"), d("Elmadağ"), d("Ayas"), d("Çubuk")] },
  { label: "Antalya",        value: "Antalya",         districts: [d("Muratpaşa"), d("Kepez"), d("Konyaaltı"), d("Alanya"), d("Manavgat"), d("Kaş"), d("Serik"), d("Akseki"), d("Elmalı"), d("Finike"), d("Gazipaşa"), d("Gündoğmuş"), d("İbradı"), d("Kale"), d("Kemer"), d("Kumluca"), d("Demre")] },
  { label: "Ardahan",        value: "Ardahan",         districts: [d("Merkez"), d("Göle"), d("Posof"), d("Çıldır")] },
  { label: "Artvin",         value: "Artvin",          districts: [d("Merkez"), d("Hopa"), d("Arhavi"), d("Borçka")] },
  { label: "Aydın",          value: "Aydın",           districts: [d("Efeler"), d("Nazilli"), d("Kuşadası"), d("Söke"), d("Didim"), d("Çine"), d("İncirliova"), d("Koçarlı"), d("Kuyucak"), d("Sultanhisar"), d("Bozdoğan")] },
  { label: "Balıkesir",      value: "Balıkesir",       districts: [d("Altıeylül"), d("Karesi"), d("Bandırma"), d("Edremit"), d("Ayvalık"), d("Susurluk"), d("Burhaniye"), d("Erdek"), d("Gönen"), d("İvrindi"), d("Kepsut"), d("Manyas"), d("Marmara")] },
  { label: "Bartın",         value: "Bartın",          districts: [d("Merkez"), d("Amasra"), d("Kurucaşile"), d("Ulus")] },
  { label: "Batman",         value: "Batman",          districts: [d("Merkez"), d("Kozluk"), d("Sason"), d("Beşiri"), d("Gercüş")] },
  { label: "Bayburt",        value: "Bayburt",         districts: [d("Merkez"), d("Aydıntepe"), d("Demirözü")] },
  { label: "Bilecik",        value: "Bilecik",         districts: [d("Merkez"), d("Bozüyük"), d("Osmaneli"), d("Söğüt")] },
  { label: "Bingöl",         value: "Bingöl",          districts: [d("Merkez"), d("Genç"), d("Kiğı"), d("Solhan")] },
  { label: "Bitlis",         value: "Bitlis",          districts: [d("Merkez"), d("Ahlat"), d("Güroymak"), d("Tatvan"), d("Adilcevaz")] },
  { label: "Bolu",           value: "Bolu",            districts: [d("Merkez"), d("Gerede"), d("Mudurnu"), d("Dörtdivan")] },
  { label: "Burdur",         value: "Burdur",          districts: [d("Merkez"), d("Bucak"), d("Gölhisar"), d("Tefenni")] },
  { label: "Bursa",          value: "Bursa",           districts: [d("Osmangazi"), d("Nilüfer"), d("Yıldırım"), d("İnegöl"), d("Mudanya"), d("Gemlik"), d("Karacabey"), d("Orhangazi"), d("Mustafakemalpaşa"), d("İznik"), d("Büyükorhan"), d("Gürsu"), d("Keles"), d("Kestel"), d("Orhaneli")] },
  { label: "Çanakkale",      value: "Çanakkale",       districts: [d("Merkez"), d("Biga"), d("Çan"), d("Gelibolu"), d("Lapseki"), d("Ayvacık"), d("Bayramiç"), d("Gökçeada"), d("Bozcaada")] },
  { label: "Çankırı",        value: "Çankırı",         districts: [d("Merkez"), d("Çerkeş"), d("Korgun"), d("Ilgaz")] },
  { label: "Çorum",          value: "Çorum",           districts: [d("Merkez"), d("Sungurlu"), d("İskilip"), d("Osmancık")] },
  { label: "Denizli",        value: "Denizli",         districts: [d("Merkezefendi"), d("Pamukkale"), d("Çivril"), d("Acıpayam"), d("Honaz"), d("Sarayköy"), d("Buldan"), d("Tavas"), d("Güney"), d("Çal"), d("Bekilli")] },
  { label: "Diyarbakır",     value: "Diyarbakır",      districts: [d("Bağlar"), d("Kayapınar"), d("Sur"), d("Yenişehir"), d("Bismil"), d("Çermik"), d("Çınar"), d("Ergani"), d("Lice"), d("Silvan"), d("Eğil")] },
  { label: "Düzce",          value: "Düzce",           districts: [d("Merkez"), d("Akçakoca"), d("Kaynaşlı"), d("Gölyaka"), d("Cumayeri")] },
  { label: "Edirne",         value: "Edirne",          districts: [d("Merkez"), d("Keşan"), d("Uzunköprü"), d("İpsala"), d("Havsa"), d("Lalapaşa"), d("Süloğlu")] },
  { label: "Elâzığ",         value: "Elâzığ",          districts: [d("Merkez"), d("Kovancılar"), d("Karakoçan"), d("Sivrice"), d("Palu")] },
  { label: "Erzincan",       value: "Erzincan",        districts: [d("Merkez"), d("Refahiye"), d("Tercan"), d("Kemah"), d("İliç")] },
  { label: "Erzurum",        value: "Erzurum",         districts: [d("Yakutiye"), d("Aziziye"), d("Palandöken"), d("Oltu"), d("Horasan"), d("Pasinler"), d("İspir"), d("Narman"), d("Olur"), d("Şenkaya"), d("Tortum")] },
  { label: "Eskişehir",      value: "Eskişehir",       districts: [d("Tepebaşı"), d("Odunpazarı"), d("Sivrihisar"), d("Çifteler"), d("Mahmudiye"), d("İnönü"), d("Mihalgazi"), d("Alpu")] },
  { label: "Gaziantep",      value: "Gaziantep",       districts: [d("Şahinbey"), d("Şehitkamil"), d("Nizip"), d("Islahiye"), d("Nurdağı"), d("Oğuzeli"), d("Araban"), d("Karkamış"), d("Yavuzeli")] },
  { label: "Giresun",        value: "Giresun",         districts: [d("Merkez"), d("Bulancak"), d("Espiye"), d("Görele"), d("Tirebolu"), d("Şebinkarahisar")] },
  { label: "Gümüşhane",      value: "Gümüşhane",       districts: [d("Merkez"), d("Kelkit"), d("Şiran"), d("Kürtün")] },
  { label: "Hakkari",        value: "Hakkari",         districts: [d("Merkez"), d("Çukurca"), d("Şemdinli"), d("Yüksekova")] },
  { label: "Hatay",          value: "Hatay",           districts: [d("Antakya"), d("İskenderun"), d("Defne"), d("Dörtyol"), d("Reyhanlı"), d("Samandağ"), d("Kırıkhan"), d("Payas"), d("Erzin"), d("Altınözü"), d("Yayladağı"), d("Hassa"), d("Kumlu"), d("Arsuz"), d("Belen")] },
  { label: "Iğdır",          value: "Iğdır",           districts: [d("Merkez"), d("Aralık"), d("Tuzluca"), d("Karakoyunlu")] },
  { label: "Isparta",        value: "Isparta",         districts: [d("Merkez"), d("Şarkikaraağaç"), d("Yalvaç"), d("Eğirdir"), d("Senirkent"), d("Sütçüler"), d("Aksu"), d("Gelendost"), d("Gönen"), d("Keçiborlu")] },
  { label: "İstanbul",       value: "İstanbul",        districts: [d("Adalar"), d("Arnavutköy"), d("Ataşehir"), d("Avcılar"), d("Bağcılar"), d("Bahçelievler"), d("Bakırköy"), d("Başakşehir"), d("Bayrampaşa"), d("Beşiktaş"), d("Beykoz"), d("Beylikdüzü"), d("Beyoğlu"), d("Büyükçekmece"), d("Çatalca"), d("Çekmeköy"), d("Esenler"), d("Esenyurt"), d("Eyüpsultan"), d("Fatih"), d("Gaziosmanpaşa"), d("Güngören"), d("Kadıköy"), d("Kağıthane"), d("Kartal"), d("Küçükçekmece"), d("Maltepe"), d("Pendik"), d("Sancaktepe"), d("Sarıyer"), d("Silivri"), d("Sultanbeyli"), d("Sultangazi"), d("Şile"), d("Şişli"), d("Tuzla"), d("Ümraniye"), d("Üsküdar"), d("Zeytinburnu")] },
  { label: "İzmir",          value: "İzmir",           districts: [d("Konak"), d("Karabağlar"), d("Bornova"), d("Buca"), d("Karşıyaka"), d("Çiğli"), d("Gaziemir"), d("Balçova"), d("Bayraklı"), d("Narlıdere"), d("Güzelbahçe"), d("Torbalı"), d("Kemalpaşa"), d("Menderes"), d("Aliağa"), d("Bergama"), d("Çeşme"), d("Dikili"), d("Foça"), d("Karaburun"), d("Kınık"), d("Kiraz"), d("Menemen"), d("Ödemiş"), d("Seferihisar"), d("Selçuk"), d("Tire"), d("Urla"), d("Bayındır"), d("Beydağ"), d("Kıyıcık")] },
  { label: "Kahramanmaraş",  value: "Kahramanmaraş",   districts: [d("Dulkadiroğlu"), d("Onikişubat"), d("Elbistan"), d("Afşin"), d("Andırın"), d("Göksun"), d("Pazarcık"), d("Türkoğlu"), d("Çağlayancerit")] },
  { label: "Karabük",        value: "Karabük",         districts: [d("Merkez"), d("Safranbolu"), d("Yenice"), d("Eflani")] },
  { label: "Karaman",        value: "Karaman",         districts: [d("Merkez"), d("Ermenek"), d("Ayrancı"), d("Kazımkarabekir")] },
  { label: "Kars",           value: "Kars",            districts: [d("Merkez"), d("Sarıkamış"), d("Kağızman"), d("Selim"), d("Arpaçay")] },
  { label: "Kastamonu",      value: "Kastamonu",       districts: [d("Merkez"), d("Taşköprü"), d("Tosya"), d("Cide"), d("Boyabat")] },
  { label: "Kayseri",        value: "Kayseri",         districts: [d("Melikgazi"), d("Kocasinan"), d("Talas"), d("İncesu"), d("Develi"), d("Pınarbaşı"), d("Yahyalı"), d("Yeşilhisar"), d("Sarıoğlan"), d("Felahiye"), d("Özvatan"), d("Tomarza"), d("Akkışla"), d("Bünyan")] },
  { label: "Kırıkkale",      value: "Kırıkkale",       districts: [d("Merkez"), d("Delice"), d("Keskin"), d("Bahşili")] },
  { label: "Kırklareli",     value: "Kırklareli",      districts: [d("Merkez"), d("Lüleburgaz"), d("Vize"), d("Babaeski"), d("Pınarhisar"), d("Demirköy")] },
  { label: "Kırşehir",       value: "Kırşehir",        districts: [d("Merkez"), d("Kaman"), d("Mucur"), d("Çiçekdağı")] },
  { label: "Kilis",          value: "Kilis",           districts: [d("Merkez"), d("Elbeyli"), d("Musabeyli"), d("Polateli")] },
  { label: "Kocaeli",        value: "Kocaeli",         districts: [d("İzmit"), d("Gebze"), d("Gölcük"), d("Körfez"), d("Başiskele"), d("Darıca"), d("Çayırova"), d("Kandıra"), d("Dilovası"), d("Karamürsel"), d("Kartepe")] },
  { label: "Konya",          value: "Konya",           districts: [d("Meram"), d("Selçuklu"), d("Karatay"), d("Ereğli"), d("Akşehir"), d("Beyşehir"), d("Cihanbeyli"), d("Ilgın"), d("Karapınar"), d("Kulu"), d("Seydişehir"), d("Yunak"), d("Doğanhisar"), d("Bozkır"), d("Çumra"), d("Derbent"), d("Derebucak"), d("Güneysınır"), d("Hadim"), d("Hüyük"), d("Kadınhanı"), d("Sarayönü"), d("Taşkent"), d("Tuzlukçu"), d("Yalıhüyük")] },
  { label: "Kütahya",        value: "Kütahya",         districts: [d("Merkez"), d("Tavşanlı"), d("Simav"), d("Gediz"), d("Domaniç"), d("Emet"), d("Hisarcık"), d("Pazarlar"), d("Şaphane")] },
  { label: "Malatya",        value: "Malatya",         districts: [d("Battalgazi"), d("Yeşilyurt"), d("Akçadağ"), d("Arapgir"), d("Arguvan"), d("Darende"), d("Doğanşehir"), d("Hekimhan"), d("Kuluncak"), d("Pütürge"), d("Yazıhan"), d("Doğanyol")] },
  { label: "Manisa",         value: "Manisa",          districts: [d("Şehzadeler"), d("Yunusemre"), d("Akhisar"), d("Salihli"), d("Turgutlu"), d("Alaşehir"), d("Soma"), d("Demirci"), d("Kula"), d("Gördes"), d("Kırkağaç"), d("Köprübaşı"), d("Sarıgöl"), d("Saruhanlı"), d("Selendi")] },
  { label: "Mardin",         value: "Mardin",          districts: [d("Artuklu"), d("Kızıltepe"), d("Nusaybin"), d("Midyat"), d("Derik"), d("Mazıdağı"), d("Savur"), d("Dargeçit"), d("Yeşilli"), d("Ömerli")] },
  { label: "Mersin",         value: "Mersin",          districts: [d("Akdeniz"), d("Mezitli"), d("Toroslar"), d("Yenişehir"), d("Tarsus"), d("Erdemli"), d("Silifke"), d("Mut"), d("Anamur"), d("Aydıncık"), d("Bozyazı"), d("Çamlıyayla"), d("Gülnar")] },
  { label: "Muğla",          value: "Muğla",           districts: [d("Menteşe"), d("Bodrum"), d("Fethiye"), d("Marmaris"), d("Milas"), d("Dalaman"), d("Ortaca"), d("Datça"), d("Seydikemer"), d("Kavaklıdere"), d("Ula"), d("Yatağan")] },
  { label: "Muş",            value: "Muş",             districts: [d("Merkez"), d("Malazgirt"), d("Varto"), d("Bulanık"), d("Hasköy"), d("Korkut")] },
  { label: "Nevşehir",       value: "Nevşehir",        districts: [d("Merkez"), d("Ürgüp"), d("Avanos"), d("Derinkuyu"), d("Gülşehir"), d("Hacıbektaş"), d("Kozaklı"), d("Acıgöl")] },
  { label: "Niğde",          value: "Niğde",           districts: [d("Merkez"), d("Bor"), d("Çamardı"), d("Ulukışla"), d("Altunhisar"), d("Çiftlik")] },
  { label: "Ordu",           value: "Ordu",            districts: [d("Altınordu"), d("Ünye"), d("Fatsa"), d("Perşembe"), d("Akkuş"), d("Aybastı"), d("Çamaş"), d("Çaybaşı"), d("Çatalpınar"), d("Gölköy"), d("Gülyalı"), d("Gürgentepe"), d("İkizce"), d("Kabadüz"), d("Kabataş"), d("Korgan"), d("Kumru"), d("Mesudiye"), d("Ulubey")] },
  { label: "Osmaniye",       value: "Osmaniye",        districts: [d("Merkez"), d("Kadirli"), d("Dörtyol"), d("İslahiye"), d("Düziçi"), d("Bahçe"), d("Hasanbeyli")] },
  { label: "Rize",           value: "Rize",            districts: [d("Merkez"), d("Fındıklı"), d("Çayeli"), d("Ardeşen"), d("Güneysu"), d("Hemşin"), d("İkizdere"), d("İyidere"), d("Kalkandere"), d("Pazar")] },
  { label: "Sakarya",        value: "Sakarya",         districts: [d("Adapazarı"), d("Arifiye"), d("Erenler"), d("Serdivan"), d("Hendek"), d("Karasu"), d("Sapanca"), d("Geyve"), d("Karapürçek"), d("Kaynarca"), d("Kocaali"), d("Pamukova"), d("Taraklı"), d("Ferizli"), d("Söğütlü")] },
  { label: "Samsun",         value: "Samsun",          districts: [d("İlkadım"), d("Canik"), d("Tekkeköy"), d("Atakum"), d("Bafra"), d("Çarşamba"), d("Havza"), d("Alaçam"), d("Asarcık"), d("Ayvacık"), d("Kavak"), d("Ladik"), d("Ondokuzmayıs"), d("Salıpazarı"), d("Terme"), d("Vezirköprü"), d("Yakakent")] },
  { label: "Siirt",          value: "Siirt",           districts: [d("Merkez"), d("Baykan"), d("Eruh"), d("Kurtalan"), d("Pervari"), d("Şirvan"), d("Tillo")] },
  { label: "Sinop",          value: "Sinop",           districts: [d("Merkez"), d("Boyabat"), d("Durağan"), d("Gerze"), d("Ayancık"), d("Dikmen"), d("Erfelek"), d("Saraydüzü"), d("Türkeli")] },
  { label: "Sivas",          value: "Sivas",           districts: [d("Merkez"), d("Şarkışla"), d("Yıldızeli"), d("Zara"), d("Gemerek"), d("Gürün"), d("İmranlı"), d("Kangal"), d("Koyulhisar"), d("Suşehri"), d("Divriği"), d("Doğanşar"), d("Hafik"), d("Ulaş"), d("Altınyayla"), d("Akıncılar")] },
  { label: "Şanlıurfa",      value: "Şanlıurfa",       districts: [d("Eyyübiye"), d("Haliliye"), d("Karaköprü"), d("Siverek"), d("Viranşehir"), d("Birecik"), d("Bozova"), d("Ceylanpınar"), d("Halfeti"), d("Harran"), d("Hilvan"), d("Suruç"), d("Akçakale")] },
  { label: "Şırnak",         value: "Şırnak",          districts: [d("Merkez"), d("Cizre"), d("Silopi"), d("İdil"), d("Uludere"), d("Beytüşşebap"), d("Güçlükonak")] },
  { label: "Tekirdağ",       value: "Tekirdağ",        districts: [d("Süleymanpaşa"), d("Kapaklı"), d("Ergene"), d("Çerkezköy"), d("Çorlu"), d("Hayrabolu"), d("Malkara"), d("Muratlı"), d("Saray"), d("Marmara Ereğlisi"), d("Şarköy")] },
  { label: "Tokat",          value: "Tokat",           districts: [d("Merkez"), d("Erbaa"), d("Niksar"), d("Turhal"), d("Zile"), d("Almus"), d("Artova"), d("Başçiftlik"), d("Pazar"), d("Reşadiye"), d("Sulusaray"), d("Yeşilyurt")] },
  { label: "Trabzon",        value: "Trabzon",         districts: [d("Ortahisar"), d("Akçaabat"), d("Araklı"), d("Arsin"), d("Beşikdüzü"), d("Çarşıbaşı"), d("Çaykara"), d("Dernekpazarı"), d("Düzköy"), d("Hayrat"), d("Köprübaşı"), d("Maçka"), d("Tonya"), d("Of"), d("Sürmene"), d("Vakfıkebir"), d("Yomra")] },
  { label: "Tunceli",        value: "Tunceli",         districts: [d("Merkez"), d("Çemişgezek"), d("Hozat"), d("Mazgirt"), d("Ovacık"), d("Pertek"), d("Pülümür")] },
  { label: "Uşak",           value: "Uşak",            districts: [d("Merkez"), d("Banaz"), d("Eşme"), d("Karahallı"), d("Sivaslı"), d("Ulubey")] },
  { label: "Van",            value: "Van",             districts: [d("İpekyolu"), d("Tuşba"), d("Edremit"), d("Erciş"), d("Gevaş"), d("Gürpınar"), d("Bahçesaray"), d("Başkale"), d("Çatak"), d("Çaldıran"), d("Muradiye"), d("Özalp"), d("Saray")] },
  { label: "Yalova",         value: "Yalova",          districts: [d("Merkez"), d("Çiftlikkoy"), d("Altınova"), d("Armutlu"), d("Çınarcık"), d("Termal")] },
  { label: "Yozgat",         value: "Yozgat",          districts: [d("Merkez"), d("Sorgun"), d("Akdağmadeni"), d("Yerköy"), d("Boğazlıyan"), d("Çekerek"), d("Sarıkaya"), d("Şefaatli"), d("Kadışehri"), d("Çayıralan"), d("Saraykent"), d("Aydıncık")] },
  { label: "Zonguldak",      value: "Zonguldak",       districts: [d("Merkez"), d("Ereğli"), d("Kdz. Ereğli"), d("Çaycuma"), d("Devrek"), d("Alaplı"), d("Gökçebey")] },
];
