import { Icon } from "@/components/Icon";
import { usePetPremium } from "@/contexts/PetPremiumContext";
import { apiCreateMedication, apiDeleteMedication, apiGetMedications, type ApiMedication } from "@/lib/petManagementApi";
import { LinearGradient } from "expo-linear-gradient";
import { useLocalSearchParams, useRouter } from "expo-router";
import React, { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Modal, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

const P="#7C45D9", BG="#F6F1FF", DARK="#211733", MUTED="#8C8699";

export default function MedicationsScreen() {
  const { petId } = useLocalSearchParams<{petId:string}>();
  const router=useRouter(), insets=useSafeAreaInsets();
  const { isPremium }=usePetPremium();
  const [items,setItems]=useState<ApiMedication[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false);
  const [name,setName]=useState(""),[dosage,setDosage]=useState(""),[times,setTimes]=useState("");
  const load=useCallback(async()=>{if(!petId)return;setLoading(true);try{setItems(await apiGetMedications(petId));}finally{setLoading(false)}},[petId]);
  useEffect(()=>{load()},[load]);
  const add=async()=>{if(!petId||!name.trim())return;try{const row=await apiCreateMedication(petId,{name:name.trim(),dosage:dosage.trim(),instructions:"",startDate:new Date().toISOString().slice(0,10),endDate:"",scheduleTimes:times.split(",").map(x=>x.trim()).filter(Boolean),recurrenceRule:"daily",reminderEnabled:true,isActive:true});setItems(v=>[row,...v]);setOpen(false);setName("");setDosage("");setTimes("");}catch(e){Alert.alert(e instanceof Error&&e.message==="premium_required"?"Evcilim Premium":"Kaydedilemedi",e instanceof Error&&e.message==="premium_required"?"Yeni ilaç ve akıllı doz hatırlatıcıları Premium üyeliğe dahildir.":"Lütfen tekrar deneyin.")}};
  const requestAdd=()=>isPremium?setOpen(true):router.push("/evcilim-premium");
  return <View style={s.root}>
    <View style={[s.header,{paddingTop:insets.top+12}]}><Pressable style={s.circle} onPress={()=>router.back()}><Icon name="chevron-back" size={22} color={DARK}/></Pressable><View style={{flex:1}}><Text style={s.title}>İlaçlar</Text><Text style={s.sub}>Doz ve kullanım saatlerini takip et</Text></View><Pressable style={s.add} onPress={requestAdd}><Icon name={isPremium?"add":"lock-closed"} size={21} color="#FFF"/></Pressable></View>
    {!isPremium&&<Pressable style={s.premium} onPress={()=>router.push("/evcilim-premium")}><Icon name="diamond-outline" size={20} color={P}/><View style={{flex:1}}><Text style={s.premiumTitle}>Premium ilaç takibi</Text><Text style={s.premiumSub}>Mevcut kayıtların görünür kalır; yeni kayıt ve hatırlatıcı için Premium’a geç.</Text></View><Icon name="chevron-forward" size={18} color={P}/></Pressable>}
    {loading?<ActivityIndicator style={{flex:1}} color={P}/>:<FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={items.length?s.list:s.empty} ListEmptyComponent={<><Icon name="medical-outline" size={48} color={P}/><Text style={s.emptyTitle}>İlaç kaydı yok</Text><Text style={s.emptySub}>Düzenli ilaçları ve doz saatlerini ekleyebilirsin.</Text></>} renderItem={({item})=><View style={s.card}><View style={s.medIcon}><Icon name="medical-outline" size={20} color={P}/></View><View style={{flex:1}}><Text style={s.medName}>{item.name}</Text><Text style={s.medSub}>{item.dosage||"Doz belirtilmedi"}{item.scheduleTimes!=="[]"?` • ${JSON.parse(item.scheduleTimes).join(", ")}`:""}</Text></View><Pressable onPress={()=>Alert.alert("İlacı Sil",`${item.name} silinsin mi?`,[{text:"Vazgeç",style:"cancel"},{text:"Sil",style:"destructive",onPress:async()=>{if(!petId)return;await apiDeleteMedication(petId,item.id);setItems(v=>v.filter(x=>x.id!==item.id))}}])}><Icon name="trash-outline" size={18} color="#E85D6F"/></Pressable></View>}/>} 
    <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={s.overlay}><View style={s.modal}><Text style={s.modalTitle}>İlaç Ekle</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="İlaç adı"/><TextInput style={s.input} value={dosage} onChangeText={setDosage} placeholder="Doz (örn. 1 tablet)"/><TextInput style={s.input} value={times} onChangeText={setTimes} placeholder="Saatler (örn. 09:00, 21:00)"/><View style={s.actions}><Pressable style={s.cancel} onPress={()=>setOpen(false)}><Text>Vazgeç</Text></Pressable><Pressable style={s.save} onPress={add}><Text style={s.saveText}>Kaydet</Text></Pressable></View></View></View></Modal>
  </View>;
}

const s=StyleSheet.create({root:{flex:1,backgroundColor:BG},header:{flexDirection:"row",alignItems:"center",gap:12,paddingHorizontal:20,paddingBottom:14},circle:{width:40,height:40,borderRadius:20,backgroundColor:"#FFF",alignItems:"center",justifyContent:"center"},title:{fontSize:19,fontFamily:"Inter_700Bold",color:DARK},sub:{fontSize:12,fontFamily:"Inter_400Regular",color:MUTED},add:{width:40,height:40,borderRadius:20,backgroundColor:P,alignItems:"center",justifyContent:"center"},premium:{marginHorizontal:20,marginBottom:12,padding:14,borderRadius:18,backgroundColor:"#F0E6FF",flexDirection:"row",alignItems:"center",gap:10},premiumTitle:{fontSize:14,fontFamily:"Inter_700Bold",color:DARK},premiumSub:{fontSize:11,fontFamily:"Inter_400Regular",color:MUTED,lineHeight:16,marginTop:2},list:{paddingHorizontal:20,paddingBottom:30},empty:{flexGrow:1,alignItems:"center",justifyContent:"center",padding:40},emptyTitle:{fontSize:18,fontFamily:"Inter_700Bold",color:DARK,marginTop:12},emptySub:{fontSize:13,fontFamily:"Inter_400Regular",color:MUTED,textAlign:"center",marginTop:6},card:{backgroundColor:"#FFF",borderRadius:17,padding:15,marginBottom:10,flexDirection:"row",alignItems:"center",gap:12},medIcon:{width:42,height:42,borderRadius:21,backgroundColor:"#F1E8FF",alignItems:"center",justifyContent:"center"},medName:{fontSize:15,fontFamily:"Inter_700Bold",color:DARK},medSub:{fontSize:12,fontFamily:"Inter_400Regular",color:MUTED,marginTop:4},overlay:{flex:1,backgroundColor:"rgba(31,18,47,.35)",justifyContent:"center",padding:24},modal:{backgroundColor:"#FFF",borderRadius:24,padding:20,gap:12},modalTitle:{fontSize:19,fontFamily:"Inter_700Bold",color:DARK},input:{height:50,borderRadius:14,backgroundColor:BG,paddingHorizontal:14,fontFamily:"Inter_400Regular",color:DARK},actions:{flexDirection:"row",gap:10,marginTop:4},cancel:{flex:1,height:48,borderRadius:14,backgroundColor:"#F3EFF7",alignItems:"center",justifyContent:"center"},save:{flex:1,height:48,borderRadius:14,backgroundColor:P,alignItems:"center",justifyContent:"center"},saveText:{color:"#FFF",fontFamily:"Inter_700Bold"}});
